[programs.localnet]
hydra_staking = "DBCBgzzZWTucUAjcAjktEjtucVPhyUpZFYKmWtvR8vHe"
hydra_pools = "4rr8xm9bVQcF2qSdBYUrHrbtk9CCcSb9zJWkX96zZmc3"
hydra_farming = "69mopwXnfh5QrWUfFbMYdvzD6CMKMqSqjqWnrXFw6NEQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 30000