[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 90000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
# From: https://pyth.network/markets/#Crypto.SOL/USD
address = "ALP8SdU9oARYVLgLR7LrqMNCYBnhtnQz1cj6bwgwQmgj" # sol product account
[[test.validator.clone]]
# From: https://pyth.network/markets/#Crypto.SOL/USD
address = "H6ARHf6YXhGYeQfUzQNGk6rDNnLBQKrenN712K4AQJEG" # sol price account
