[workspace]
members = [
    "programs/*",
    "sdks/hydra-math-rs",
    "sdks/wasm-loader-ts/wasm-test",
    "libs/math/hmm",
    "libs/math/hydra-proto",
    "libs/math/sim",
#    "tools/*" # Removed until we have the space to build this out.
]
