cargo-features = ["edition2021"]

[package]
name = "hydra-pools"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "hydra_pools"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.18.2"
solana-program = "=1.8.1"
hydra-math = { version = "0.1.0", path = "../../libs/hmm", features = ["no-entrypoint"] }
