name: anchor-build
env:
  cli-id: anchor-v0.18.dev-7b86aed-solana-1.8.5
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  build-cli-deps:
    runs-on: ubuntu-latest
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor
            ~/.cargo/bin/wasm-pack

      - id: install-os-deps
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev tree make

      - id: install-rust-toolchain
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - id: install-solana-tools
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV

      - id: install-anchor-cli
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: cargo install --git https://github.com/project-serum/anchor.git anchor-cli --locked

      - id: install-wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "v0.10.2"
  build:
    runs-on: ubuntu-latest
    needs: [build-cli-deps]
    steps:
      - id: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor
            ~/.cargo/bin/wasm-pack

      - id: install-os-deps
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev tree make

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - id: install-yarn
        run: npm install -g yarn

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
      - id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - id: cache-turbo-folders
        uses: actions/cache@v2
        with:
          path: "**/.turbo"
          key: ${{ runner.os }}-turbo-files

      - run: make anchor-ci

      - name: Notify slask success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: ANCHOR-SUCCESS
          color: good

      - name: Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: ANCHOR-FAILED
          color: danger
