name: anchor-build
env:
  cache-id: anchor-20220305a
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  build-cli-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: yellowmegaman/gh-build-canceller@v1.6
        name: kill-old-builds
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflows_filter: "CI|pr|build-cli-deps"

      - id: cache-cli-deps
        name: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cache-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor
            ~/.cargo/bin/wasm-pack

      - id: checkout
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: install-os-deps
        name: install-os-deps
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev tree make

      - id: install-rust-toolchain
        name: install-rust-toolchain
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - id: install-wasm-pack
        name: install-wasm-pack
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: make install_wasm_pack

      - id: install-solana-tools
        name: install-solana-tools
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: make install_solana

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV

      - id: install-anchor-cli
        name: install-anchor-cli
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: make install_anchor

      - id: install-yarn
        name: install-yarn
        run: npm install -g yarn

  build:
    runs-on: ubuntu-latest
    needs: [build-cli-deps]
    steps:
      - uses: yellowmegaman/gh-build-canceller@v1.6
        name: kill-old-builds
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflows_filter: "CI|pr|build"

      - id: cache-cli-deps
        name: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cache-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor
            ~/.cargo/bin/wasm-pack

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
      - id: cache-node-modules
        name: cache-node-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - id: cache-turbo-folders
        name: cache-turbo-folders
        uses: actions/cache@v2
        with:
          path: "**/.turbo"
          key: ${{ runner.os }}-turbo-files

      - run: make anchor-ci

      - name: Notify slask success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: ANCHOR-SUCCESS
          color: good

      - name: Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: ANCHOR-FAILED
          color: danger
