# File: .github/workflows/kill_stale.yml
name: build_canceller
on:
  pull_request:
jobs:
  build_canceller:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: kill_stale_builds
        uses: yellowmegaman/gh-build-canceller@v1.6
        with:
          github_token: ${{secrets.PERSONAL_TOKEN}}
          workflows_filter: "CI|pr"
