name: react-build
env:
  cli-id: react-v17.0.2
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
jobs:
  build-cli-deps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - id: yarn-cache
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}-yarn-${{ hashFiles('app/yarn.lock') }}
          path: ${{ steps.yarn-cache-dir.outputs.dir }}

      - id: install-os-deps
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev tree

      - id: install-node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - id: install-yarn
        run: npm install -g yarn

      - id: install-node-yarn-cache
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: yarn
      
  build:
    runs-on: ubuntu-latest
    needs: [build-cli-deps]
    steps:
      - id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - id: yarn-cache
        uses: actions/cache@v2
        with:
          key: $${{ env.cli-id }}-yarn-${{ hashFiles('app/yarn.lock') }}
          path: ${{ steps.yarn-cache-dir.outputs.dir }}

      - id: install-os-deps
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev tree make

      - id: install-ipfs-deploy
        run: npm install -g ipfs-deploy

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: make react-ci-cd

      - name: Notify slask success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: REACT-SUCCESS
          color: good

      - name: Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: REACT-FAILED
          color: danger

