name: react-build
env:
  cache-id: react-20220427a
  CARGO_TERM_COLOR: always
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"
jobs:
  build-js-deps:
    runs-on: ubuntu-latest
    steps:
      - id: cache-cli-deps
        name: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cache-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor
            ~/.cargo/bin/wasm-pack

      - id: checkout
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: install-os-deps
        name: install-os-deps
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev tree make

      - id: install-rust-toolchain
        name: install-rust-toolchain
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.60.0

      - id: install-solana-tools
        name: install-solana-tools
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: make install_solana

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$PATH" >> $GITHUB_ENV

      - id: install-anchor-cli
        name: install-anchor-cli
        if: steps.cache-cli-deps.outputs.cache-hit != 'true'
        run: make install_anchor

      - id: install-node
        name: install-node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - id: install-yarn
        name: install-yarn
        run: npm install -g yarn

      - id: install-serve
        name: install-serve
        run: npm install -g serve

  build-js-stack:
    runs-on: ubuntu-latest
    needs: [build-js-deps]
    steps:
      - id: cache-cli-deps
        name: cache-cli-deps
        uses: actions/cache@v2
        with:
          key: $${{ env.cache-id }}
          path: |
            ~/.local/share/solana
            ~/.cargo
            ~/.rustup
            ~/.cargo/bin/anchor
            ~/.cargo/bin/wasm-pack

      - run: echo "PATH=$HOME/.local/share/solana/install/active_release/bin:$HOME/.cargo/bin:$PATH" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: install-wasm-pack
        name: install-wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0
        with:
          version: "v0.10.2"

      # https://dev.to/mpocock1/how-to-cache-nodemodules-in-github-actions-with-yarn-24eh
      - id: cache-node-modules
        name: cache-node-modules
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - id: cache-turbo-folders
        name: cache-turbo-folders
        uses: actions/cache@v2
        with:
          path: "**/.turbo"
          key: ${{ runner.os }}-turbo-files

      - id: install-playwright
        name: install-playwright
        run: yarn install --frozen-lockfile && cd app && yarn playwright install

      - id: install-ipfs-deploy
        name: install-ipfs-deploy
        run: npm install -g ipfs-deploy

      - run: make react-ci
        name: react-ci

      - name: react-ci Notify slask success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: REACT-CI-SUCCESS
          color: good

      - name: react-ci - Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: REACT-CI-FAILED
          color: danger

      - id: ipfs-deploy
        name: ipfs-deploy
        uses: aquiladev/ipfs-action@v0.2.1
        with:
          service: infura
          path: ./app/build

      - run: echo ${{steps.ipfs-deploy.outputs.cid}}

      - name: react-cd - Notify slask success
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: REACT-CD-SUCCESS https://ipfs.infura.io/ipfs/${{steps.ipfs-deploy.outputs.cid}}
          color: good

      - name: react-cd - Notify slack failure
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: gitops
          status: REACT-CD-FAILED
          color: danger
